### PR TITLE
Perseuspy Network support

### PR DESCRIPTION
**Pull request by deiluca**
Added perseusNetwork.py for reading/ writing networks, network examples, unittests and a Readme extension...

### CODE REVIEW

**Comment by jdrudolph** [comment]
make sure that the CI build is passing (failing at the moment).
You can see in the logs that your dependency `networkx` is missing. Make sure to add it to the dependencies in `setup.py`.

**Comment by jdrudolph** [comment]
looks good!
Just one more thing. I don't think it's necessary to write the test output to real files. Instead output should be written to e.g. a file-like `io.StringIO` object. See for example https://github.com/jdrudolph/perseuspy/blob/master/perseuspy/test/test_io.py .
The last step would be to make sure all public functions and modules are properly documented and generate the updated documentation using the `generate_docs.sh`.

**Review by jdrudolph — CHANGES_REQUESTED** [review]
there is a easy way to get rid of these windows/linux file path issues, namely using `os.path.join` etc. for everything related to paths. https://docs.python.org/3/library/os.path.html

**Comment by deiluca** [comment]
Ah thank you, this would be way nicer. Ok then I know what I have to do...

**Review by jdrudolph — CHANGES_REQUESTED** [review]
use `os.path.join` to join file paths i.e. `pd.read_perseus(os.path.join(inFolder, 'networks.txt'))`

**Comment by deiluca** [comment]
Ah I remember, no I fixed it, just need to commit

**Comment by deiluca** [comment]
Writing not to objects for testing, I need to think about (can't imagine this at the moment for my structure).  Will do this next week... See you

**Review by jdrudolph — DISMISSED** [review]

**Comment by jdrudolph** [comment]
There are still some inconsistencies with the documentation...
Function docstring should follow sphinx autodoc syntax. See `read_perseus(...)` for an example. Once all docstrings are finished the documentation should be updated by running the `generate_documentation.sh` script.

**Comment by deiluca** [comment]
I added the docstrings, also ran the .sh locally. As the script doesn't fully run on my pc, I didn't add the created files in /docs yet. Just for info... :)

**Comment by deiluca** [comment]
Hi, I am a bit confused about the documentation: So I ran the generate_documentation.sh and got the .html files (in /docs/_build) that are displaying the documentation (so I think). As you ignore the builded .html files (.gitignore), how is the documentation thought to show up in github? Needs the index.rst to be extended (only includes the README.txt)?

**Comment by jdrudolph** [comment]
you should not add any files from the `_build` folder to the repository. Only the generated You can read http://read-the-docs.readthedocs.io/en/latest/getting_started.html for reference.

**Comment by jdrudolph** [comment]
closed by 81efd31

**Pull request closed without merging**
